---
# Installs OpenJDK
# Corresponds to docker layer: https://github.com/jboss-dockerfiles/base-jdk
- name: Install OpenJDK - yum
  sudo: true
  yum:
    name: "{{ 'java-' + java_version + '.0-openjdk-devel' }}"
    state: latest
#  when: os1_distro_variant == 'rhel' or os1_distro_variant == 'centos'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install OpenJDK - dnf
  sudo: true
  dnf:
    name: "{{ 'java-' + java_version + '.0-openjdk-devel' }}"
    state: latest
  when: ansible_distribution == 'Fedora'
